name: Close inactive issues
on:
  workflow_dispatch:

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 0
          days-before-issue-close: 0
          stale-issue-label: "stale"
          operations-per-run: 1000
          repo-token: ${{ secrets.GITHUB_TOKEN }}
